/**
 * As métricas que só o chat alcança (perguntas de CFO, 2026-09-03).
 *
 * O catálogo tem uma regra: toda métrica é alcançável por algum caminho — uma
 * intenção do Anexo B, um cartão de KPI, ou uma nota de painel. As métricas
 * das perguntas de CFO da Dreamy entraram sem cartão: respondem no chat, e é
 * o chat quem as alcança. Esta lista nomeia cada uma, e dois testes a
 * sustentam pelos dois lados — nenhuma métrica do catálogo fica órfã, e cada
 * uma daqui é alvo de pelo menos uma pergunta do conjunto de roteamento.
 *
 * Quando ganharem cartão, saem daqui. Quando entrarem no Anexo B, também.
 */
export const SO_NO_CHAT: readonly string[] = [
  "patrimonio_liquido",
  "ativo_total",
  "ativo_circulante",
  "passivo_circulante",
  "imobilizado",
  "aplicacoes_financeiras",
  "divida_curto_prazo",
  "divida_longo_prazo",
  "divida_bruta",
  "divida_liquida",
  "capital_investido",
  "estoque_sem_giro",
  "a_receber_vencido",
  "a_pagar_vencido",
  "contas_a_receber",
  "contas_a_pagar",
  "juros_pagos",
  "impostos_sobre_lucro",
  "amortizacao_de_divida",
  "distribuicao_a_socios",
  "roe",
  "roa",
  "resultado_operacional_liquido",
  "roic",
  "giro_do_ativo",
  "multiplicador_de_capital",
  "liquidez_corrente",
  "liquidez_seca",
  "liquidez_imediata",
  "dias_de_caixa",
  "ncg",
  "saldo_de_tesouraria",
  "caixa_excedente",
  "divida_liquida_sobre_ebitda",
  "divida_sobre_pl",
  "cobertura_de_juros",
  "cobertura_do_servico_da_divida",
  "custo_medio_da_divida",
  "custo_liquido_da_divida",
  "custo_do_prazo_de_recebimento",
  "custo_de_carregar_estoque",
  "fluxo_de_caixa_livre",
  "variacao_de_capital_de_giro",
  "divida_capital_de_giro",
  "divida_financiamento_longo_prazo",
  "divida_antecipacao_de_recebiveis",
  // Etapa 2: natureza das contas e qualidade do razão
  "custos_fixos",
  "custos_variaveis",
  "margem_de_contribuicao",
  "margem_de_contribuicao_valor",
  "ponto_de_equilibrio",
  "ponto_de_equilibrio_caixa",
  "ponto_de_equilibrio_economico",
  "margem_de_seguranca",
  "gao",
  "resultado_com_receita_10_menor",
  "lancamentos_do_mes",
  "lancamentos_para_revisao",
  "valor_para_revisao",
  "lancamentos_fora_do_padrao",
  "lancamentos_em_conta_parada",
  "pares_de_estorno",
  "lancamentos_de_competencia_anterior",
  "completude_da_base",
  "valor_sem_centro_de_custo",
  "valor_em_conta_generica",
  "valor_sem_natureza",
  "indicios_de_competencia",
  "efeito_no_resultado_da_competencia",
  "contas_recorrentes_sem_lancamento",
  "lancamentos_duplicados",
  "contas_com_classificacao_inconsistente",
  "valor_em_classificacao_inconsistente",
  "movimentacao_com_partes_relacionadas",
  "roe_sem_partes_relacionadas",
  "mutuo_com_socios",
  "receita_dos_principais_clientes",
];
