/**
 * O catálogo de métricas, em TypeScript (T-120).
 *
 * **GERADO. Não edite.** A fonte é `catalogo/metricas.yaml`, que é o arquivo
 * que Controladoria e RH revisam (seção 9.4). Para mudar uma métrica, mude o
 * YAML e rode `npm run catalogo`.
 *
 * Existe porque `getMetric` precisa do catálogo em execução, e o YAML não
 * entra no pacote de produção. `npm run catalogo:check` roda na build e
 * reprova se este arquivo estiver atrasado em relação ao YAML — sem isso,
 * editar a definição de uma métrica e esquecer de regerar deixaria o produto
 * servindo a definição antiga, em silêncio.
 */

import type { Metrica } from "@/semantica/catalogo";

export const CATALOGO_GERADO: Readonly<Record<string, Metrica>> = {
  a_pagar_vencido: {
    id: "a_pagar_vencido",
    rotulo: "A pagar vencido",
    fonte: "vw_fato_contas",
    formula: "soma(a_pagar nas faixas vencidas, fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "a pagar vencido",
      "fornecedores vencidos",
      "fornecedores com vencimento passado",
      "atraso com fornecedor",
    ],
    decisao:
      'PROVISORIO (D-H03, 2026-09-03). Tudo fora de "a vencer". E o numero que separa negociacao de atraso na pergunta de PMP do documento de CFO.',
  },
  a_receber_vencido: {
    id: "a_receber_vencido",
    rotulo: "A receber vencido",
    fonte: "vw_fato_contas",
    formula: "soma(a_receber nas faixas vencidas, fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "a receber vencido",
      "recebiveis vencidos",
      "carteira vencida",
      "vencido a receber",
    ],
    decisao:
      'PROVISORIO (D-H03, 2026-09-03). Tudo fora de "a vencer", desde 1 dia -- diferente da inadimplencia, que conta so acima de 90 dias.',
  },
  absenteismo: {
    id: "absenteismo",
    rotulo: "Absenteísmo",
    fonte: "vw_fato_rh_mes",
    formula: "soma(horas_ausentes) / soma(horas_previstas)",
    unidade: "pct",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: ["absenteismo", "faltas", "ausencia", "afastamento", "atestado"],
    decisao:
      'PROVISORIO (D-H03, 2026-08-24). O que entra em "horas ausentes" -- ferias, licenca medica, falta injustificada -- muda o numero e nao esta definido. Precisa de RH em H-08.',
  },
  amortizacao_de_divida: {
    id: "amortizacao_de_divida",
    rotulo: "Amortização de dívida",
    fonte: "vw_fato_balanco_mes",
    formula: "soma(amortizacao_de_divida)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "amortizacao",
      "amortizacao de divida",
      "parcelas da divida",
      "principal pago",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Principal pago no periodo, 130 no ano em doze parcelas. Com a distribuicao e a captacao fecha o FCF de 80.",
  },
  aplicacoes_financeiras: {
    id: "aplicacoes_financeiras",
    rotulo: "Aplicações financeiras",
    fonte: "vw_fato_balanco_mes",
    formula: "aplicacoes_financeiras(fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["aplicacoes financeiras", "caixa aplicado", "aplicacoes"],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). A parte do caixa que esta aplicada e sai do capital investido. Na fixture e uma fracao fixa do saldo de caixa.",
  },
  ativo_circulante: {
    id: "ativo_circulante",
    rotulo: "Ativo circulante",
    fonte: "vw_fato_balanco_mes",
    formula: "ativo_circulante(fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["ativo circulante", "o que a empresa tem de curto prazo"],
    decisao:
      'PROVISORIO (D-H03, 2026-09-03). Caixa e aplicacoes, a receber, estoque e outros circulantes. O que entra em "outros" e pergunta de H-08.',
  },
  ativo_total: {
    id: "ativo_total",
    rotulo: "Ativo total",
    fonte: "vw_fato_balanco_mes",
    formula: "ativo_total(fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["ativo total", "bens e direitos", "total de ativos"],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). E a identidade contabil: passivo circulante mais divida de longo prazo mais patrimonio. Precisa de Controladoria em H-08.",
  },
  beneficios: {
    id: "beneficios",
    rotulo: "Benefícios",
    fonte: "vw_fato_rh_mes",
    formula: "soma(beneficios)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: ["beneficios", "saude", "alimentacao", "transporte", "pacote"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Parcela da folha, e nao despesa a parte. Somar a folha com os beneficios contaria os beneficios duas vezes.",
  },
  caixa_excedente: {
    id: "caixa_excedente",
    rotulo: "Caixa excedente",
    fonte: "vw_fato_fin_mes, vw_fato_contas",
    formula: "saldo_de_caixa - ncg (fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "caixa excedente",
      "caixa que excede",
      "sobra de caixa",
      "quanto do caixa e excedente",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). O que pode ficar aplicado sem faltar para a operacao. Negativo e caixa insuficiente para o giro.",
  },
  capex: {
    id: "capex",
    rotulo: "Investimento (FCI)",
    fonte: "vw_fato_fin_mes",
    formula: "soma(capex)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["capex", "investimento", "fci", "manutencao e expansao"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Positivo e SAIDA de caixa. Sentido neutro porque investir mais nao e bom nem ruim sozinho -- depende do retorno, que esta fora do escopo da v1.",
  },
  capital_investido: {
    id: "capital_investido",
    rotulo: "Capital investido",
    fonte: "vw_fato_balanco_mes",
    formula:
      "patrimonio_liquido + divida_bruta - aplicacoes_financeiras (fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "capital investido",
      "capital que trabalha na operacao",
      "dinheiro dos socios e dos bancos",
    ],
    decisao:
      'PROVISORIO (D-H03, 2026-09-03). "Todo o dinheiro que esta de fato trabalhando dentro da empresa, tirando o caixa que so esta aplicado", como o documento de CFO define. Precisa de Controladoria em H-08.',
  },
  ciclo_financeiro: {
    id: "ciclo_financeiro",
    rotulo: "Ciclo de conversão de caixa",
    fonte: "vw_fato_contas",
    formula:
      "pmr + pme - pmp, com pmr = a_receber / receita_liquida * 365, pme = estoque / cmv * 365 e pmp = a_pagar / cmv * 365",
    unidade: "dias",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["ciclo", "ciclo financeiro", "ciclo de conversao de caixa"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Usa 365 dias e o CMV como denominador de PME e PMP. Compras do periodo seria o denominador mais correto para o PMP, e a fixture nao tem essa medida. Precisa de Controladoria em H-08.",
  },
  cobertura_da_pesquisa: {
    id: "cobertura_da_pesquisa",
    rotulo: "Cobertura da pesquisa",
    fonte: "vw_fato_rh_mes",
    formula: "soma(respondentes) / soma(elegiveis)",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "cobertura",
      "quantos responderam",
      "adesao a pesquisa",
      "taxa de resposta",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). E o numero que qualifica todos os outros de clima: eNPS e engajamento falam pelos 74% que responderam.",
  },
  cobertura_de_juros: {
    id: "cobertura_de_juros",
    rotulo: "Cobertura de juros",
    fonte: "vw_fato_fin_mes, vw_fato_balanco_mes",
    formula: "(ebitda - depreciacao_e_amortizacao) / juros_pagos (recorte)",
    unidade: "vezes",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "cobertura de juros",
      "consegue pagar os juros",
      "pagar os juros",
      "quantas vezes os juros",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). EBIT sobre juros. Da 1,0 vez no ano: os juros consomem todo o EBIT, como o cartao de lucro liquido ja dizia.",
  },
  cobertura_do_servico_da_divida: {
    id: "cobertura_do_servico_da_divida",
    rotulo: "Cobertura do serviço da dívida",
    fonte: "vw_fato_fin_mes, vw_fato_balanco_mes",
    formula:
      "(ebitda - depreciacao_e_amortizacao) / (juros_pagos + amortizacao_de_divida) (recorte)",
    unidade: "vezes",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "cobertura do servico da divida",
      "servico da divida",
      "juros mais amortizacao",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). E o numero que diz se vai apertar: com as amortizacoes, cai abaixo de 1.",
  },
  concentracao_top_10: {
    id: "concentracao_top_10",
    rotulo: "Concentração top 10",
    fonte: "vw_fato_faturamento_cliente",
    formula: "soma(receita) / soma(vw_fato_fin_mes.receita_liquida)",
    unidade: "pct",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "concentracao",
      "top 10",
      "dependencia de cliente",
      "risco de carteira",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Sentido `menor_melhor`: concentracao e risco. Os dez sao fixos e nao os dez do recorte -- sob recorte mensal o ranking pode ser outro, e recalcula-lo mudaria o que a metrica mede.",
  },
  conclusao_treinamento: {
    id: "conclusao_treinamento",
    rotulo: "Conclusão média",
    fonte: "vw_fato_treinamento",
    formula: "soma(trilhas_concluidas) / soma(trilhas_iniciadas)",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "conclusao",
      "terminou a trilha",
      "evasao",
      "abandono",
      "completou",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Trilha iniciada num mes e concluida no seguinte fecha no mes da conclusao. Sob recorte mensal isso pode passar de 100% -- e a razao de a metrica existir com grao mensal e ser lida em 12m.",
  },
  contas_a_pagar: {
    id: "contas_a_pagar",
    rotulo: "Contas a pagar",
    fonte: "vw_fato_contas",
    formula: "soma(a_pagar, fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "contas a pagar",
      "a pagar",
      "fornecedores a pagar",
      "saldo a pagar",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Saldo total com fornecedores, todas as faixas de aging. Fecha em 101 em dezembro.",
  },
  contas_a_receber: {
    id: "contas_a_receber",
    rotulo: "Contas a receber",
    fonte: "vw_fato_contas",
    formula: "soma(a_receber, fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "contas a receber",
      "a receber",
      "clientes a receber",
      "saldo a receber",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Saldo total da carteira, todas as faixas de aging. Fecha em 171 em dezembro.",
  },
  conversao_de_caixa: {
    id: "conversao_de_caixa",
    rotulo: "Conversão de caixa",
    fonte: "vw_fato_fin_mes",
    formula:
      "soma(fco) / (soma(receita_liquida) - soma(cmv) - soma(despesas_operacionais))",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "conversao",
      "fco sobre ebitda",
      "virou caixa",
      "qualidade do lucro",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Denominador e o EBITDA calculado, nao uma coluna. Em mes de EBITDA proximo de zero a razao explode -- o motivo denominador_zero de T-182 existe para esse caso.",
  },
  crescimento_yoy: {
    id: "crescimento_yoy",
    rotulo: "Crescimento anual",
    fonte: "vw_fato_fin_mes",
    formula: "receita_liquida(ano) / receita_liquida(ano anterior) - 1",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "crescimento",
      "yoy",
      "ano contra ano",
      "ano anterior",
      "evolucao da receita",
      "cresceu",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Comparacao contra o mesmo periodo do ano anterior, nao contra o periodo imediatamente anterior. Nao aprovado por Controladoria: a sessao e H-08.",
  },
  custo_de_carregar_estoque: {
    id: "custo_de_carregar_estoque",
    rotulo: "Custo de carregar o estoque",
    fonte: "vw_fato_fin_mes, vw_fato_balanco_mes",
    formula: "estoque(fim) * custo_medio_da_divida / 12",
    unidade: "BRL_mi",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "custo de carregar estoque",
      "custo do estoque parado",
      "financiar o estoque",
      "quanto custa o estoque",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Por mes, ao custo medio da divida. Nao aparece na DRE como tal.",
  },
  custo_de_reposicao: {
    id: "custo_de_reposicao",
    rotulo: "Custo de reposição",
    fonte: "vw_fato_rh_mes",
    formula: "soma(custo_de_reposicao)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "reposicao",
      "ramp-up",
      "curva de aprendizado",
      "produtividade perdida",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). E a parcela do custo do turnover que nao aparece em nota fiscal nenhuma: ramp-up e produtividade perdida. Justamente por isso e a que gera discussao.",
  },
  custo_do_prazo_de_recebimento: {
    id: "custo_do_prazo_de_recebimento",
    rotulo: "Custo do prazo de recebimento",
    fonte: "vw_fato_contas, vw_fato_balanco_mes",
    formula: "contas_a_receber(fim) * custo_medio_da_divida / 12",
    unidade: "BRL_mi",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "custo do prazo de recebimento",
      "custo de financiar o cliente",
      "cada dia de prazo custa",
      "quanto custa o prazo",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Por mes: o que custa financiar a carteira ao custo medio da divida. E leitura, nao lancamento.",
  },
  custo_do_turnover: {
    id: "custo_do_turnover",
    rotulo: "Custo do turnover",
    fonte: "vw_fato_rh_mes",
    formula: "soma(custo_de_reposicao) + soma(custo_de_desligamento)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "custo do turnover",
      "quanto custa perder gente",
      "custo de rotatividade",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Soma rescisao, ramp-up, produtividade perdida e recrutamento de reposicao. A parcela de recrutamento vale R$ 1,9 mi e o KPI de custo por contratacao vale R$ 0,83 mi no ano -- dois custos de recrutamento com o mesmo nome curto e despesas diferentes.",
  },
  custo_liquido_da_divida: {
    id: "custo_liquido_da_divida",
    rotulo: "Custo líquido da dívida",
    fonte: "vw_fato_balanco_mes",
    formula: "custo_medio_da_divida * (1 - 34%)",
    unidade: "pct",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "custo liquido da divida",
      "custo da divida depois do beneficio fiscal",
      "custo da divida liquido de imposto",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Beneficio fiscal a 34% (IR e CSLL do lucro real), que e a aliquota nominal e nao a efetiva de uma empresa com prejuizo. Precisa de Controladoria em H-08.",
  },
  custo_medio_da_divida: {
    id: "custo_medio_da_divida",
    rotulo: "Custo médio da dívida",
    fonte: "vw_fato_balanco_mes",
    formula:
      "juros_pagos(recorte, anualizado) / media(divida_bruta no recorte)",
    unidade: "pct",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "custo medio da divida",
      "custo da divida",
      "taxa media da divida",
      "quanto estamos pagando de juros",
      "juros estao caros",
      "isso esta caro",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Taxa efetiva, todas as linhas juntas: da 15,6% no ano. O chat a le como spread sobre o CDI.",
  },
  custo_por_contratacao: {
    id: "custo_por_contratacao",
    rotulo: "Custo por contratação",
    fonte: "vw_fato_vagas",
    formula: "soma(custo_de_recrutamento) / soma(contratados)",
    unidade: "BRL_mi",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "custo por contratacao",
      "custo de recrutamento",
      "quanto custa contratar",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Conta so contratacao EFETIVADA, entao vaga cancelada joga o custo dela sobre as que fecharam -- que e o comportamento correto e nem sempre o esperado.",
  },
  custo_por_fte: {
    id: "custo_por_fte",
    rotulo: "Custo por FTE",
    fonte: "vw_fato_rh_mes",
    formula: "soma(folha) / soma(headcount_fte do ultimo mes do recorte)",
    unidade: "BRL_mi",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "custo por fte",
      "custo por colaborador",
      "quanto custa cada pessoa",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Denominador e o quadro do FIM do recorte, nao o quadro medio. Numa empresa que cresce, o medio da um custo por pessoa maior -- e a escolha muda o numero em ano de contratacao forte.",
  },
  custo_por_hora_treinamento: {
    id: "custo_por_hora_treinamento",
    rotulo: "Custo por hora",
    fonte: "vw_fato_treinamento",
    formula: "soma(investimento) / soma(horas)",
    unidade: "BRL_mi",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "custo por hora",
      "quanto custa a hora",
      "preco do treinamento",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Sentido `menor_melhor` trata hora barata como melhor, e hora barata costuma ser hora online -- que o proprio dataset mostra concluindo 58% contra 86% do presencial.",
  },
  desligamentos: {
    id: "desligamentos",
    rotulo: "Desligamentos",
    fonte: "vw_fato_rh_mes",
    formula: "soma(desligamentos)",
    unidade: "contagem",
    agg: "sum",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "desligamentos",
      "saidas",
      "demissoes",
      "quem saiu",
      "quantos sairam",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Herda a indefinicao de P2 (H-06): se transferencia interna contar como desligamento, este numero sobe e o turnover sobe junto.",
  },
  desvio_orcamentario: {
    id: "desvio_orcamentario",
    rotulo: "Desvio orçamentário",
    fonte: "vw_fato_orcamento",
    formula: "soma(realizado) - soma(orcado)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["centro_custo", "mes"],
    sinonimos: ["desvio", "orcamento", "estouro", "centro de custo"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Positivo e estouro. O sentido `menor_melhor` trata gastar menos que o orcado como melhor, o que nem sempre e verdade -- economia por projeto nao executado tambem aparece assim. E uma das definicoes que precisam de Controladoria em H-08.",
  },
  dias_de_caixa: {
    id: "dias_de_caixa",
    rotulo: "Dias de caixa",
    fonte: "vw_fato_fin_mes",
    formula:
      "saldo_de_caixa(fim) / (saidas_de_caixa(recorte) / dias do recorte)",
    unidade: "dias",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["dias de caixa", "cobre quantos dias", "caixa cobre"],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Quantos dias de desembolso medio o caixa atual cobre. Usa 30 dias por mes.",
  },
  distribuicao_a_socios: {
    id: "distribuicao_a_socios",
    rotulo: "Distribuição aos sócios",
    fonte: "vw_fato_balanco_mes",
    formula: "soma(distribuicao_a_socios)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "distribuicao aos socios",
      "dividendos",
      "retirada dos socios",
      "distribuicao de lucros",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Dez no ano, de uma vez em abril. Sai do patrimonio e do caixa.",
  },
  distribuicao_etaria: {
    id: "distribuicao_etaria",
    rotulo: "Distribuição por faixa etária",
    fonte: "vw_dim_faixa_etaria",
    formula: "headcount_fte quebrado por faixa etaria",
    unidade: "FTE",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["faixa", "mes"],
    sinonimos: [
      "idade",
      "faixa etaria",
      "tempo de casa",
      "escolaridade",
      "senioridade",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). A view de dimensao ainda nao existe -- e T-147. A secao 11 exige que faixa com menos de 5 pessoas nao seja exibida, e quem aplica isso e T-151.",
  },
  distribuicao_uf: {
    id: "distribuicao_uf",
    rotulo: "Distribuição por estado",
    fonte: "vw_dim_uf",
    formula: "headcount_fte quebrado por unidade federativa",
    unidade: "FTE",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["uf", "mes"],
    sinonimos: [
      "estado",
      "uf",
      "geografia",
      "mapa",
      "onde estao",
      "distribuicao geografica",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). A view de dimensao ainda nao existe -- e T-147.",
  },
  divida_antecipacao_de_recebiveis: {
    id: "divida_antecipacao_de_recebiveis",
    rotulo: "Antecipação de recebíveis",
    fonte: "vw_fato_divida_mes",
    formula: "saldo(linha = antecipacao-de-recebiveis, fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["antecipacao de recebiveis", "antecipacao", "linha mais cara"],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Curto prazo, a 24% ao ano na fixture: a linha mais cara, e a primeira a trocar.",
  },
  divida_bruta: {
    id: "divida_bruta",
    rotulo: "Dívida bruta",
    fonte: "vw_fato_balanco_mes",
    formula: "divida_curto_prazo + divida_longo_prazo (fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "divida bruta",
      "divida total",
      "emprestimos e financiamentos",
      "quanto devemos ao banco",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Soma das linhas de credito. Fecha em 900 em dezembro, 300 de curto e 600 de longo prazo.",
  },
  divida_capital_de_giro: {
    id: "divida_capital_de_giro",
    rotulo: "Linha de capital de giro",
    fonte: "vw_fato_divida_mes",
    formula: "saldo(linha = capital-de-giro, fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "linha de capital de giro",
      "saldo de capital de giro",
      "emprestimo de capital de giro",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Curto prazo, a 18% ao ano na fixture.",
  },
  divida_curto_prazo: {
    id: "divida_curto_prazo",
    rotulo: "Dívida de curto prazo",
    fonte: "vw_fato_balanco_mes",
    formula: "divida_curto_prazo(fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "divida de curto prazo",
      "vence em ate 12 meses",
      "divida que vence este ano",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Capital de giro e antecipacao de recebiveis. Vencimento em ate 12 meses, como o documento de CFO le.",
  },
  divida_financiamento_longo_prazo: {
    id: "divida_financiamento_longo_prazo",
    rotulo: "Financiamento de longo prazo",
    fonte: "vw_fato_divida_mes",
    formula: "saldo(linha = financiamento-longo-prazo, fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["financiamento de longo prazo", "linha de longo prazo"],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Longo prazo, a 13,3% ao ano na fixture: a linha mais barata.",
  },
  divida_liquida: {
    id: "divida_liquida",
    rotulo: "Dívida líquida",
    fonte: "vw_fato_balanco_mes, vw_fato_fin_mes",
    formula: "divida_bruta - saldo_de_caixa (fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["divida liquida", "divida descontado o caixa"],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Desconta caixa E aplicacoes, que e o saldo de caixa da ponte. Precisa de Controladoria em H-08.",
  },
  divida_liquida_sobre_ebitda: {
    id: "divida_liquida_sobre_ebitda",
    rotulo: "Dívida líquida sobre EBITDA",
    fonte: "vw_fato_balanco_mes, vw_fato_fin_mes",
    formula: "divida_liquida(fim do recorte) / ebitda(recorte, anualizado)",
    unidade: "vezes",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "divida liquida sobre ebitda",
      "alavancagem",
      "endividamento",
      "endividamento esta alto",
      "vezes o ebitda",
      "anos para quitar",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). O EBITDA do recorte e anualizado para o multiplo fazer sentido sob um mes. As faixas de leitura (ate 2, 2 a 3, acima de 3) sao do documento de CFO e ficam com o modelo, nao com o dado.",
  },
  divida_longo_prazo: {
    id: "divida_longo_prazo",
    rotulo: "Dívida de longo prazo",
    fonte: "vw_fato_balanco_mes",
    formula: "divida_longo_prazo(fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["divida de longo prazo", "vence depois de 12 meses"],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). O financiamento de longo prazo. Precisa de Controladoria em H-08.",
  },
  divida_sobre_pl: {
    id: "divida_sobre_pl",
    rotulo: "Dívida sobre patrimônio",
    fonte: "vw_fato_balanco_mes",
    formula: "divida_bruta / patrimonio_liquido (fim do recorte)",
    unidade: "vezes",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "divida sobre patrimonio",
      "divida sobre pl",
      "relacao divida patrimonio",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). A alavancagem que amplifica o ROE: da 2,6 vezes em dezembro.",
  },
  ebitda: {
    id: "ebitda",
    rotulo: "EBITDA",
    fonte: "vw_fato_fin_mes",
    formula: "soma(receita_liquida) - soma(cmv) - soma(despesas_operacionais)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["ebitda", "lajida", "resultado antes de juros"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Obtido por diferenca, e nao por soma de contas. Nao existe coluna de EBITDA: se existisse, seria possivel ela discordar das tres parcelas que a formam.",
  },
  ebitda_por_fte: {
    id: "ebitda_por_fte",
    rotulo: "EBITDA per capita",
    fonte: "vw_fato_fin_mes, vw_fato_rh_mes",
    formula:
      "(soma(receita_liquida) - soma(cmv) - soma(despesas_operacionais)) / headcount_fte(ultimo mes)",
    unidade: "BRL_mi",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["ebitda per capita", "ebitda por fte", "resultado por pessoa"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Cruza duas views, e por isso herda o grao da mais grossa: receita nao tem area, entao a razao tambem nao tem. Quebrar por area exigiria ratear receita por quadro -- ver H-04 e T-144.",
  },
  economia_orcamentaria: {
    id: "economia_orcamentaria",
    rotulo: "Economia obtida",
    fonte: "vw_fato_orcamento",
    formula:
      "soma de (orcado - realizado) apenas nos centros de custo onde a diferenca e positiva",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["centro_custo", "mes"],
    sinonimos: [
      "economia",
      "sobra de orcamento",
      "gastou menos",
      "abaixo do orcado",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Conta SO os centros que gastaram menos, ignorando os que estouraram -- por isso nao e o desvio com sinal trocado. Sentido `maior_melhor` trata economizar como bom, e economia por projeto nao executado aparece igual. E uma das definicoes que precisam de Controladoria em H-08.",
  },
  encargos_sobre_salarios: {
    id: "encargos_sobre_salarios",
    rotulo: "Encargos",
    fonte: "vw_fato_rh_mes",
    formula: "soma(encargos) / soma(salarios)",
    unidade: "pct",
    agg: "ratio",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "encargos",
      "tributos sobre folha",
      "custo trabalhista",
      "inss e fgts",
    ],
    decisao:
      'PROVISORIO (D-H03, 2026-08-24). Sobre SALARIOS, e nao sobre a folha: 37,5% contra 22,6%. Os dois sao "percentual de encargos" em portugues, e um deles aparece numa negociacao sindical.',
  },
  engajamento_area: {
    id: "engajamento_area",
    rotulo: "Engajamento por área",
    fonte: "vw_fato_rh_mes",
    formula: "soma(pontos_de_engajamento) / soma(respondentes)",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "engajamento",
      "clima",
      "satisfacao",
      "pesquisa de clima",
      "moral",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Media ponderada por respondente, e nao media das medias por area -- as duas dao numeros diferentes quando as areas tem tamanhos diferentes. A cobertura da pesquisa e de 74% do quadro, e o numero fala pelos que responderam.",
  },
  engajamento_minimo_por_area: {
    id: "engajamento_minimo_por_area",
    rotulo: "Área mais crítica",
    fonte: "vw_fato_rh_mes",
    formula:
      "o menor valor de soma(pontos_de_engajamento) / soma(respondentes) entre as areas do recorte",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "area critica",
      "pior area",
      "menor engajamento",
      "onde esta o problema",
    ],
    decisao:
      'PROVISORIO (D-H03, 2026-08-24). E um minimo entre areas, e nao uma media: sob recorte de uma area so, o minimo e a propria area. A secao 11 exige grupo de ao menos 5 pessoas, e area pequena pode virar a "mais critica" por ruido amostral -- T-151 trata a supressao.',
  },
  enps: {
    id: "enps",
    rotulo: "eNPS",
    fonte: "vw_fato_rh_mes",
    formula: "(soma(promotores) - soma(detratores)) / soma(respondentes) * 100",
    unidade: "pontos",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: ["enps", "nps interno", "detratores", "recomendaria a empresa"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Unidade `pontos`, que entrou no enum em 2026-08-24 (D-H45): o eNPS vai de -100 a +100 e e a diferenca entre duas proporcoes, entao `pct` afirmaria que ele e uma proporcao. Nao se soma ao longo do periodo.",
  },
  escolaridade_superior: {
    id: "escolaridade_superior",
    rotulo: "Superior ou mais",
    fonte: "vw_fato_rh_perfil",
    formula:
      "soma(headcount_fte em superior, pos-graduacao e mestrado-mais) / soma(headcount_fte em todos os niveis)",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "escolaridade",
      "formacao",
      "superior",
      "graduacao",
      "titulacao",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). INCLUI mestrado, e da 51,6%. O prototipo mostra 48,9%, que e Superior mais Pos SEM mestrado -- mestrado e superior ou mais. Registrado em H-48.",
  },
  estados_atendidos: {
    id: "estados_atendidos",
    rotulo: "Estados atendidos",
    fonte: "vw_fato_rh_perfil",
    formula: "contagem de UFs com headcount_fte maior que zero no recorte",
    unidade: "contagem",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["uf", "mes"],
    sinonimos: [
      "estados",
      "uf",
      "cobertura geografica",
      "onde tem gente",
      "capilaridade",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Conta estado com QUALQUER pessoa, sem piso. A secao 11 exige suprimir grupo com menos de 5 pessoas na EXIBICAO da faixa; a contagem de estados nao expoe o grupo, so a existencia dele.",
  },
  estoque_sem_giro: {
    id: "estoque_sem_giro",
    rotulo: "Estoque sem giro",
    fonte: "vw_fato_balanco_mes",
    formula: "estoque_sem_giro(fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "estoque sem giro",
      "itens sem movimentacao",
      "estoque encalhado",
      "sem movimentacao ha mais de 90 dias",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Itens sem movimentacao ha mais de 90 dias. Na fixture e uma fracao fixa do estoque; o corte de dias e pergunta de H-08.",
  },
  fco: {
    id: "fco",
    rotulo: "Geração operacional",
    fonte: "vw_fato_fin_mes",
    formula: "soma(fco)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "fco",
      "geracao de caixa",
      "caixa operacional",
      "virou dinheiro",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Caixa que a operacao gerou, e nao lucro. A diferenca entre os dois e o capital de giro, que e onde o ciclo de 76 dias aparece.",
  },
  financiamento: {
    id: "financiamento",
    rotulo: "Financiamento (FCF)",
    fonte: "vw_fato_fin_mes",
    formula: "soma(financiamento)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["fcf", "financiamento", "captacao", "financiamento liquido"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Positivo e SAIDA liquida -- amortizacao e juros menos captacao. A fixture nao separa as tres, e separa-las e uma das perguntas de H-08.",
  },
  fluxo_de_caixa_livre: {
    id: "fluxo_de_caixa_livre",
    rotulo: "Fluxo de caixa livre",
    fonte: "vw_fato_fin_mes",
    formula: "soma(fco) - soma(capex)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "fluxo de caixa livre",
      "caixa livre",
      "por que o caixa nao melhora",
      "ebitda esta bom",
      "sobra de caixa depois do investimento",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). O que sobra da operacao depois de investir: 185 - 140 = 45 no ano.",
  },
  folha_sobre_receita: {
    id: "folha_sobre_receita",
    rotulo: "Despesa de pessoal",
    fonte: "vw_fato_rh_mes, vw_fato_fin_mes",
    formula: "soma(folha) / soma(vw_fato_fin_mes.receita_liquida)",
    unidade: "pct",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "folha sobre receita",
      "despesa de pessoal",
      "custo de pessoal",
      "peso da folha",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Da 15,5% -- o numero do Anexo C. Sentido `menor_melhor` trata folha menor como melhor, o que ignora que cortar gente tambem corta receita. E o tipo de leitura que a tela de Integracao existe para complicar de proposito.",
  },
  folha_total: {
    id: "folha_total",
    rotulo: "Folha total",
    fonte: "vw_fato_rh_mes",
    formula: "soma(folha)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "folha",
      "custo de pessoal",
      "salarios",
      "quanto custa a equipe",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). A base de competencia da rescisao esta indefinida -- e a decisao P3, item H-07. A escolha muda a folha de todo mes com desligamento, e com ela folha sobre receita e custo por colaborador.",
  },
  giro_do_ativo: {
    id: "giro_do_ativo",
    rotulo: "Giro do ativo",
    fonte: "vw_fato_fin_mes, vw_fato_balanco_mes",
    formula: "receita_liquida(recorte) / ativo_total(fim do recorte)",
    unidade: "vezes",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["giro do ativo", "giro", "quanto vende por real investido"],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). A segunda peca do DuPont. Sob recorte mensal nao anualiza.",
  },
  headcount_fte: {
    id: "headcount_fte",
    rotulo: "Headcount FTE",
    fonte: "vw_fato_rh_mes",
    formula: "saldo_de_abertura + soma(admissoes - desligamentos, ate o mes)",
    unidade: "FTE",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "headcount",
      "quadro",
      "fte",
      "pessoas",
      "colaboradores",
      "tamanho do time",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Estoque, nao fluxo: o quadro de marco e a soma das areas em marco, nunca a soma de janeiro a marco. Sentido neutro porque crescer nao e bom nem ruim sozinho -- depende da receita.",
  },
  horas_por_fte: {
    id: "horas_por_fte",
    rotulo: "Horas por FTE",
    fonte: "vw_fato_treinamento",
    formula: "soma(horas) / soma(vw_fato_rh_mes.headcount_fte do ultimo mes)",
    unidade: "horas",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: ["horas por fte", "horas por pessoa", "treinamento per capita"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Divide pelo quadro INTEIRO, e nao so por quem treinou: e a leitura de alcance, nao de intensidade. Dividir por quem treinou daria outro numero e outra conversa.",
  },
  horas_treinamento: {
    id: "horas_treinamento",
    rotulo: "Horas de treinamento",
    fonte: "vw_fato_treinamento",
    formula: "soma(horas)",
    unidade: "horas",
    agg: "sum",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "treinamento",
      "horas de treinamento",
      "capacitacao",
      "desenvolvimento",
      "trilhas",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Unidade `horas`, que entrou no enum em 2026-08-24 (D-H45). Sentido `maior_melhor` trata mais horas como melhor, o que ignora a conclusao -- o proprio dataset mostra 21.400 horas com 64% de conclusao. Precisa de RH em H-08.",
  },
  idade_media: {
    id: "idade_media",
    rotulo: "Idade média",
    fonte: "vw_fato_rh_mes",
    formula: "soma(soma_de_idade) / soma(headcount_fte)",
    unidade: "anos",
    agg: "ratio",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "idade",
      "idade media",
      "faixa etaria",
      "quantos anos",
      "perfil etario",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Media do quadro no fechamento do recorte, e nao do quadro medio do periodo. Sentido neutro: quadro mais velho nao e bom nem ruim sozinho.",
  },
  imobilizado: {
    id: "imobilizado",
    rotulo: "Imobilizado",
    fonte: "vw_fato_balanco_mes",
    formula: "imobilizado(fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["imobilizado", "maquinas e sistemas", "ativo fixo"],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Abre em 760 e anda com capex menos depreciacao, fechando em 840. Intangivel esta dentro por simplificacao.",
  },
  impostos_sobre_lucro: {
    id: "impostos_sobre_lucro",
    rotulo: "Impostos sobre o lucro",
    fonte: "vw_fato_balanco_mes",
    formula: "soma(impostos_sobre_lucro)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "impostos sobre o lucro",
      "imposto de renda",
      "ir e csll",
      "quanto pagamos de imposto",
    ],
    decisao:
      'PROVISORIO (D-H03, 2026-09-03). E o degrau "nao operacional" da ponte da DRE, que o Anexo C chama de IR. Precisa de Controladoria em H-08.',
  },
  inadimplencia: {
    id: "inadimplencia",
    rotulo: "Inadimplência",
    fonte: "vw_fato_contas",
    formula:
      "a_receber(acima de 90 dias, fim da janela) / a_receber(fim da janela)",
    unidade: "pct",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["faixa", "mes"],
    sinonimos: [
      "inadimplencia",
      "aging",
      "recebiveis",
      "atraso",
      "vencido",
      "calote",
    ],
    decisao:
      'PROVISORIO (D-H03, 2026-08-24). Conta so a faixa ACIMA DE 90 DIAS, que e o que o rodape do cartao no prototipo declara: "R$ 7 mi sobre R$ 171 mi". Contar tudo fora de "a vencer" -- inclusive 1 a 30 dias -- levaria a taxa de 4,1% para 31%, e parte das empresas conta assim. E uma das definicoes que precisam de Controladoria em H-08.',
  },
  investimento_treinamento: {
    id: "investimento_treinamento",
    rotulo: "Investimento em treinamento",
    fonte: "vw_fato_treinamento",
    formula: "soma(investimento)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "investimento",
      "verba de treinamento",
      "quanto gasta em desenvolvimento",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Sentido `maior_melhor` trata gastar mais como melhor, o que ignora a conclusao -- 21.400 horas com 64% de conclusao. Precisa de RH em H-08.",
  },
  juros_pagos: {
    id: "juros_pagos",
    rotulo: "Juros pagos",
    fonte: "vw_fato_balanco_mes",
    formula: "soma(juros_pagos)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "juros pagos",
      "juros",
      "despesa financeira",
      "despesa com juros",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). E o resultado financeiro da ponte da DRE, por competencia -- a questao H-56 (caixa ou competencia) continua aberta.",
  },
  liquidez_corrente: {
    id: "liquidez_corrente",
    rotulo: "Liquidez corrente",
    fonte: "vw_fato_balanco_mes",
    formula: "ativo_circulante / passivo_circulante (fim do recorte)",
    unidade: "vezes",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["liquidez corrente", "liquidez"],
    decisao:
      'PROVISORIO (D-H03, 2026-09-03). Le-se como "para cada R$ 1,00 devido em 12 meses, R$ x disponivel". Da 0,98 em dezembro.',
  },
  liquidez_imediata: {
    id: "liquidez_imediata",
    rotulo: "Liquidez imediata",
    fonte: "vw_fato_balanco_mes, vw_fato_fin_mes",
    formula: "saldo_de_caixa / passivo_circulante (fim do recorte)",
    unidade: "vezes",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["liquidez imediata", "so o dinheiro na conta", "so o caixa"],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). So caixa e aplicacoes sobre o passivo circulante. Precisa de Controladoria em H-08.",
  },
  liquidez_seca: {
    id: "liquidez_seca",
    rotulo: "Liquidez seca",
    fonte: "vw_fato_balanco_mes, vw_fato_fin_mes",
    formula:
      "(ativo_circulante - estoque) / passivo_circulante (fim do recorte)",
    unidade: "vezes",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "liquidez seca",
      "sem contar com o estoque",
      "nao puder contar com o estoque",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Tira o estoque do circulante. Precisa de Controladoria em H-08.",
  },
  lucro_liquido: {
    id: "lucro_liquido",
    rotulo: "Lucro líquido",
    fonte: "vw_fato_fin_mes",
    formula:
      "soma(receita_liquida) - soma(cmv) - soma(despesas_operacionais) - soma(depreciacao_e_amortizacao) - soma(resultado_financeiro) - soma(nao_operacional)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "lucro liquido",
      "lucro",
      "resultado do exercicio",
      "bottom line",
      "deu lucro",
      "demos lucro",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). O ultimo degrau da ponte da DRE, derivado dos outros seis. Da -R$ 8 mi no ano: a operacao gera resultado e a estrutura de capital o anula.",
  },
  margem_bruta: {
    id: "margem_bruta",
    rotulo: "Margem bruta",
    fonte: "vw_fato_fin_mes",
    formula: "(soma(receita_liquida) - soma(cmv)) / soma(receita_liquida)",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "margem bruta",
      "lucro bruto",
      "cmv",
      "custo do produto vendido",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). O que entra no CMV -- frete, perda, depreciacao de fabrica -- muda o numero e nao esta definido. Precisa de Controladoria em H-08.",
  },
  margem_ebitda: {
    id: "margem_ebitda",
    rotulo: "Margem EBITDA",
    fonte: "vw_fato_fin_mes",
    formula:
      "(receita_liquida - cmv - despesas_operacionais) / receita_liquida",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["margem ebitda", "resultado operacional", "lucro operacional"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). EBITDA obtido por diferenca, e nao por soma de contas de resultado. Nao aprovado por Controladoria: a sessao e H-08.",
  },
  margem_liquida: {
    id: "margem_liquida",
    rotulo: "Margem líquida",
    fonte: "vw_fato_fin_mes",
    formula:
      "(soma(receita_liquida) - soma(cmv) - soma(despesas_operacionais) - soma(depreciacao_e_amortizacao) - soma(resultado_financeiro) - soma(nao_operacional)) / soma(receita_liquida)",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["margem liquida", "resultado final", "bottom line"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Derivada dos degraus da ponte da DRE, e nao de uma coluna de lucro. A serie mensal de margem liquida do prototipo nao fecha com a ponte -- da -4,3 contra -8 -- e por isso nao foi transcrita.",
  },
  mediana_salarial: {
    id: "mediana_salarial",
    rotulo: "Mediana salarial",
    fonte: "vw_fato_rh_perfil",
    formula:
      "interpolacao linear dentro da faixa salarial que contem a pessoa do meio, a partir das contagens por faixa",
    unidade: "BRL_mi",
    agg: "ratio",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["faixa", "mes"],
    sinonimos: [
      "mediana",
      "mediana salarial",
      "salario do meio",
      "metade ganha menos",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). NAO E KPI: e texto de nota do painel sal-faixas, e o aceite de T-148 a lista entre os 15 por engano -- registrado em H-48. Entra assim mesmo, porque nota com numero tambem declara formula (PR-3, RF-09). A interpolacao sobre faixas da cerca de R$ 6,0 mil contra os R$ 6.240 do prototipo; com dado real a mediana sai do salario individual e nao da faixa, e a aproximacao some.",
  },
  multiplicador_de_capital: {
    id: "multiplicador_de_capital",
    rotulo: "Multiplicador do patrimônio",
    fonte: "vw_fato_balanco_mes",
    formula: "ativo_total / patrimonio_liquido (fim do recorte)",
    unidade: "vezes",
    agg: "ratio",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "multiplicador do patrimonio",
      "multiplicador de capital",
      "alavancagem patrimonial",
      "ativo sobre patrimonio",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). A terceira peca do DuPont: quanto de ativo cada real dos socios sustenta.",
  },
  ncg: {
    id: "ncg",
    rotulo: "Necessidade de capital de giro",
    fonte: "vw_fato_contas, vw_fato_fin_mes",
    formula: "contas_a_receber + estoque - contas_a_pagar (fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "ncg",
      "necessidade de capital de giro",
      "capital de giro",
      "dinheiro parado na operacao",
      "precisa ter parado",
      "quanto precisa ter parado",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Pelos saldos, e nao pelo ciclo vezes a receita diaria -- as duas contas dao numeros diferentes, e esta e a que reconcilia com o balanco. Precisa de Controladoria em H-08.",
  },
  orcado: {
    id: "orcado",
    rotulo: "Orçado",
    fonte: "vw_fato_orcamento",
    formula: "soma(orcado)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["centro_custo", "mes"],
    sinonimos: ["orcado", "orcamento", "planejado", "budget", "previsto"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Orcamento aprovado do periodo. Revisao de orcamento no meio do ano nao esta modelada: a fixture tem uma versao so.",
  },
  participacao_treinamento: {
    id: "participacao_treinamento",
    rotulo: "Participação em treinamento",
    fonte: "vw_fato_rh_mes",
    formula: "participantes_de_treinamento(ultimo mes) / elegiveis(ultimo mes)",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "participacao",
      "quantos treinam",
      "alcance do treinamento",
      "adesao",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Denominador e o quadro ELEGIVEL, nao o quadro inteiro. Na fixture os dois coincidem; a formula nomeia o certo para que nada mude quando o dado real distinguir. Lida no ULTIMO MES da janela, e nao somada nela: pessoa nao soma ao longo do tempo, e somar dava 108,9% de participacao -- mais gente treinando do que gente.",
  },
  passivo_circulante: {
    id: "passivo_circulante",
    rotulo: "Passivo circulante",
    fonte: "vw_fato_balanco_mes",
    formula: "passivo_circulante(fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "passivo circulante",
      "obrigacoes de curto prazo",
      "o que deve em 12 meses",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). A pagar, divida de curto prazo e acrescimos (salarios, encargos e impostos a pagar). Precisa de Controladoria em H-08.",
  },
  patrimonio_liquido: {
    id: "patrimonio_liquido",
    rotulo: "Patrimônio líquido",
    fonte: "vw_fato_balanco_mes",
    formula: "patrimonio_liquido(fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "patrimonio liquido",
      "pl",
      "capital dos socios",
      "capital proprio",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Abre em 368 e anda com o lucro do mes menos a distribuicao aos socios, fechando em 350. Nao ha balanco de 2025: a comparacao com o ano anterior espera T-152.",
  },
  perfil_quadro: {
    id: "perfil_quadro",
    rotulo: "Perfil do quadro",
    fonte: "vw_fato_rh_mes",
    formula: "headcount_fte quebrado por modalidade de trabalho",
    unidade: "FTE",
    agg: "last",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["modalidade", "mes"],
    sinonimos: [
      "perfil",
      "genero",
      "modalidade",
      "presencial",
      "hibrido",
      "remoto",
      "composicao",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Hoje quebra so por modalidade de trabalho. Genero depende das dimensoes vw_dim_* de T-147.",
  },
  pme: {
    id: "pme",
    rotulo: "PME",
    fonte: "vw_fato_fin_mes",
    formula: "soma(estoque) / soma(cmv) * 365",
    unidade: "dias",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "pme",
      "prazo medio de estocagem",
      "giro de estoque",
      "estoque parado",
      "dias de estoque",
      "quanto tempo o estoque fica",
      "dio",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). O estoque nao existia no prototipo e foi DERIVADO do proprio PME declarado: 75 x 720 / 365 = 148. Quando o dado real chegar, o estoque vem da contabilidade e o PME passa a sair dele.",
  },
  pmp: {
    id: "pmp",
    rotulo: "PMP",
    fonte: "vw_fato_contas",
    formula: "soma(a_pagar) / soma(vw_fato_fin_mes.cmv) * 365",
    unidade: "dias",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "pmp",
      "prazo medio de pagamento",
      "prazo de pagamento",
      "dias para pagar",
      "pagamos os fornecedores",
      "quanto demora a pagar",
      "dpo",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Sentido `maior_melhor` -- pagar depois financia o giro. Denominador deveria ser COMPRAS do periodo, e a fixture nao tem essa medida; usa o CMV. Precisa de Controladoria em H-08.",
  },
  pmr: {
    id: "pmr",
    rotulo: "PMR",
    fonte: "vw_fato_contas",
    formula: "soma(a_receber) / soma(vw_fato_fin_mes.receita_liquida) * 365",
    unidade: "dias",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "pmr",
      "prazo medio de recebimento",
      "prazo de recebimento",
      "dias para receber",
      "recebemos dos clientes",
      "quanto demora a receber",
      "dso",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Usa 365 dias e a receita do periodo. Com recorte mensal o prazo fica anualizado sobre um mes so, o que exagera a sazonalidade. Precisa de Controladoria em H-08.",
  },
  promotores: {
    id: "promotores",
    rotulo: "Promotores",
    fonte: "vw_fato_rh_mes",
    formula: "soma(promotores) / soma(respondentes)",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: ["promotores", "quem recomenda", "nota 9 ou 10", "satisfeitos"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Fracao entre QUEM RESPONDEU, e nao entre o quadro. Com 74% de cobertura, os dois numeros diferem em um quarto.",
  },
  realizado: {
    id: "realizado",
    rotulo: "Realizado",
    fonte: "vw_fato_orcamento",
    formula: "soma(realizado)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["centro_custo", "mes"],
    sinonimos: ["realizado", "gasto", "executado", "o que saiu de fato"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). O gasto do periodo pela competencia, e nao pelo caixa -- e por isso nao bate com as saidas de caixa.",
  },
  receita_bruta: {
    id: "receita_bruta",
    rotulo: "Receita bruta",
    fonte: "vw_fato_fin_mes",
    formula: "soma(receita_bruta)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "receita bruta",
      "faturamento bruto",
      "antes das deducoes",
      "top line",
    ],
    decisao:
      'PROVISORIO (D-H03, 2026-08-24). E a receita ANTES das deducoes. O rodape do cartao diz "deducoes de 15%", e a conta e 212 sobre 1.412 -- que da 15,0%.',
  },
  receita_liquida: {
    id: "receita_liquida",
    rotulo: "Receita líquida",
    fonte: "vw_fato_fin_mes",
    formula: "soma(receita_liquida)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["receita liquida", "faturamento", "vendas", "receita"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). E o denominador de quase toda margem do produto, entao mudar o que entra nela move meia dezena de KPIs juntos.",
  },
  receita_por_fte: {
    id: "receita_por_fte",
    rotulo: "Receita por colaborador",
    fonte: "vw_fato_fin_mes, vw_fato_rh_mes",
    formula: "soma(receita_liquida) / headcount_fte(ultimo mes do recorte)",
    unidade: "BRL_mi",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "receita por colaborador",
      "produtividade",
      "receita por fte",
      "rpc",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Unica metrica que cruza duas views, e o grao dela e o da mais grossa: receita nao tem area (secao 10.1), entao a razao tambem nao tem. Quebrar por area exigiria ratear receita por quadro, que e arbitragem e nao recorte -- ver H-04 e T-144.",
  },
  remuneracao_variavel: {
    id: "remuneracao_variavel",
    rotulo: "Variável",
    fonte: "vw_fato_rh_mes",
    formula: "soma(variavel)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: ["variavel", "bonus", "comissao", "horas extras", "premiacao"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Junta bonus e horas extras, que tem origens opostas -- um premia resultado, o outro sinaliza falta de gente. Separa-los e uma das perguntas de H-08.",
  },
  resultado_operacional_liquido: {
    id: "resultado_operacional_liquido",
    rotulo: "Resultado operacional líquido",
    fonte: "vw_fato_fin_mes, vw_fato_balanco_mes",
    formula: "ebitda - depreciacao_e_amortizacao - impostos_sobre_lucro",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "resultado operacional liquido",
      "nopat",
      "ebit depois de impostos",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). O numerador do ROIC: o que a operacao rende depois do imposto e antes dos juros.",
  },
  retencao_12m: {
    id: "retencao_12m",
    rotulo: "Retenção 12 meses",
    fonte: "vw_fato_rh_mes",
    formula: "1 - turnover_12m",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: ["retencao", "permanencia", "quem fica", "quem permanece"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). E o complemento exato do turnover, entao herda a indefinicao de P2 (H-06). Se transferencia interna passar a contar como desligamento, os dois numeros mudam juntos.",
  },
  roa: {
    id: "roa",
    rotulo: "ROA",
    fonte: "vw_fato_balanco_mes, vw_fato_fin_mes",
    formula: "lucro_liquido(recorte) / ativo_total(fim do recorte)",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "roa",
      "retorno sobre o ativo",
      "retorno sobre os ativos",
      "que o roe nao diz",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). O menos manipulavel dos dois retornos: nao depende de como a empresa se financiou.",
  },
  roe: {
    id: "roe",
    rotulo: "ROE",
    fonte: "vw_fato_balanco_mes, vw_fato_fin_mes",
    formula: "lucro_liquido(recorte) / patrimonio_liquido(fim do recorte)",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "roe",
      "retorno sobre o patrimonio",
      "retorno dos socios",
      "rentabilidade do patrimonio",
      "retorno sobre o capital proprio",
      "por que o roe caiu",
      "margem, giro ou divida",
      "dupont",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Lucro do recorte sobre o patrimonio do fim -- sob recorte mensal nao anualiza. O documento de CFO le o ROE contra o CDI e descontado do IPCA; o chat faz as duas leituras.",
  },
  roic: {
    id: "roic",
    rotulo: "ROIC",
    fonte: "vw_fato_balanco_mes, vw_fato_fin_mes",
    formula:
      "resultado_operacional_liquido(recorte) / capital_investido(fim do recorte)",
    unidade: "pct",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "roic",
      "retorno sobre o capital investido",
      "cria ou destroi valor",
      "aplicar no cdi",
      "deixar o dinheiro na empresa",
      "divida esta trabalhando a nosso favor",
      "divida a favor",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). O retorno de todo o capital que trabalha na operacao. O chat o le contra o CDI liquido de IR, que e o que a aplicacao entrega de fato. O custo de capital dos socios nao esta modelado.",
  },
  salario_medio: {
    id: "salario_medio",
    rotulo: "Salário médio",
    fonte: "vw_fato_rh_mes",
    formula:
      "soma(folha, no recorte) / (media(headcount_fte, no recorte) * meses)",
    unidade: "BRL_mi",
    agg: "ratio",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "salario",
      "salario medio",
      "remuneracao",
      "faixa salarial",
      "quanto paga",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Sai da folha inteira dividida pelo quadro, entao inclui encargos, beneficios e variavel -- nao e salario contratual. A unidade e `BRL_mi` porque e a unica monetaria do enum; a escala de exibicao e da apresentacao (regra 2). Precisa de RH em H-08.",
  },
  saldo_caixa: {
    id: "saldo_caixa",
    rotulo: "Saldo de caixa",
    fonte: "vw_fato_fin_mes",
    formula:
      "saldo_inicial + soma(entradas_de_caixa - saidas_de_caixa, ate o mes)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["caixa", "saldo", "disponibilidade", "quanto tem em caixa"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Estoque: agrega por `last`, nunca por soma ao longo do periodo. Somar saldos de doze meses da um numero que nao existe.",
  },
  saldo_de_tesouraria: {
    id: "saldo_de_tesouraria",
    rotulo: "Saldo de tesouraria",
    fonte: "vw_fato_fin_mes, vw_fato_balanco_mes",
    formula: "saldo_de_caixa - divida_curto_prazo (fim do recorte)",
    unidade: "BRL_mi",
    agg: "last",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: ["saldo de tesouraria", "tesouraria", "tesouraria negativa"],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Negativo quer dizer capital de giro financiado por divida de curto prazo. Da -200 em dezembro.",
  },
  tempo_ate_a_saida: {
    id: "tempo_ate_a_saida",
    rotulo: "Tempo até a saída",
    fonte: "vw_fato_rh_mes",
    formula: "soma(soma_de_tempo_ate_a_saida) / soma(desligamentos)",
    unidade: "anos",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "tempo ate a saida",
      "quanto tempo fica",
      "sobrevivencia",
      "quando sai",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). O denominador sao os DESLIGAMENTOS, nao o quadro. Trocar os dois daria 0,25 anos -- plausivel e errado.",
  },
  tempo_fechamento: {
    id: "tempo_fechamento",
    rotulo: "Tempo médio de fechamento",
    fonte: "vw_fato_vagas",
    formula: "soma(dias_somados) / soma(fechadas)",
    unidade: "dias",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "tempo de fechamento",
      "dias para fechar",
      "time to fill",
      "demora da vaga",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Conta so vagas FECHADAS, entao vaga aberta ha muito tempo nao entra na media -- e o vies classico dessa metrica, que melhora quando as vagas dificeis simplesmente nao fecham.",
  },
  tempo_medio_de_casa: {
    id: "tempo_medio_de_casa",
    rotulo: "Tempo médio de casa",
    fonte: "vw_fato_rh_mes",
    formula: "soma(soma_de_tempo_de_casa) / soma(headcount_fte)",
    unidade: "anos",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "tempo de casa",
      "permanencia",
      "senioridade",
      "ha quanto tempo",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Conta so quem esta no quadro. Quem saiu tem metrica propria (tempo_ate_a_saida), e misturar as duas daria um numero que nao descreve nem o quadro nem a saida.",
  },
  ticket_medio: {
    id: "ticket_medio",
    rotulo: "Ticket médio",
    fonte: "vw_fato_fin_mes",
    formula: "soma(receita_liquida) / soma(notas_emitidas)",
    unidade: "BRL_mi",
    agg: "ratio",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "ticket medio",
      "valor por nota",
      "pedido medio",
      "quanto cada venda",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Nota fiscal e o denominador, nao pedido nem cliente. Uma venda faturada em tres notas conta tres vezes.",
  },
  trabalho_flexivel: {
    id: "trabalho_flexivel",
    rotulo: "Trabalho flexível",
    fonte: "vw_fato_rh_mes",
    formula: "soma(headcount_fte em hibrido e remoto) / soma(headcount_fte)",
    unidade: "pct",
    agg: "ratio",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["modalidade", "mes"],
    sinonimos: ["flexivel", "hibrido", "remoto", "home office", "presencial"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Conta hibrido COMO flexivel. Uma empresa que exige tres dias no escritorio chamaria isso de presencial, e o numero mudaria em quinze pontos.",
  },
  turnover_12m: {
    id: "turnover_12m",
    rotulo: "Turnover 12 meses",
    fonte: "vw_fato_rh_mes",
    formula: "soma(desligamentos, 12m) / media(headcount_fte, 12m)",
    unidade: "pct",
    agg: "ratio",
    sentido: "menor_melhor",
    meta: 14,
    grao_minimo: ["area", "mes"],
    sinonimos: ["turnover", "rotatividade", "saidas", "atrito", "quem sai"],
    decisao:
      'PROVISORIO (D-H03, 2026-08-24). A secao 9.4 do PRD traz, como EXEMPLO de preenchimento, a frase "transferencia interna nao conta como desligamento, aprovado por RH e Controladoria em 2026-08". Essa aprovacao nao aconteceu: a secao 18 do mesmo PRD lista P2 como decisao PENDENTE, e o item H-06 ainda esta aberto. O exemplo foi transcrito para ca em T-112 e vira afirmacao quando sai da ilustracao. Ate H-06 fechar, a regra de transferencia interna esta indefinida e o numero e mockup.',
  },
  vagas_abertas: {
    id: "vagas_abertas",
    rotulo: "Vagas abertas",
    fonte: "vw_fato_vagas",
    formula: "soma(abertas)",
    unidade: "contagem",
    agg: "sum",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "vagas abertas",
      "posicoes abertas",
      "quantas vagas",
      "em aberto",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Fluxo e nao estoque: soma as vagas ABERTAS no periodo, e nao as que estao abertas hoje. Sob recorte de 12 meses os dois numeros diferem bastante.",
  },
  vagas_canceladas: {
    id: "vagas_canceladas",
    rotulo: "Vagas canceladas",
    fonte: "vw_fato_vagas",
    formula: "soma(canceladas)",
    unidade: "contagem",
    agg: "sum",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "canceladas",
      "vagas canceladas",
      "desistiu da vaga",
      "remanejamento",
    ],
    decisao:
      'PROVISORIO (D-H03, 2026-08-24). Saem do funil sem contratacao, normalmente por remanejamento interno. Contam no denominador de "do total movimentado".',
  },
  vagas_em_andamento: {
    id: "vagas_em_andamento",
    rotulo: "Vagas em andamento",
    fonte: "vw_fato_vagas",
    formula: "soma(em_andamento)",
    unidade: "contagem",
    agg: "sum",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: ["em andamento", "triagem", "entrevistas", "processo em curso"],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Cobre da triagem a proposta. Vaga com proposta feita e nao aceita continua aqui.",
  },
  vagas_fechadas: {
    id: "vagas_fechadas",
    rotulo: "Vagas fechadas",
    fonte: "vw_fato_vagas",
    formula: "soma(fechadas)",
    unidade: "contagem",
    agg: "sum",
    sentido: "maior_melhor",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "vagas fechadas",
      "contratacoes",
      "preenchidas",
      "admissoes efetivadas",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Vaga fechada e contratacao efetivada, e o numero e igual ao de contratados do funil. Vaga cancelada nao entra.",
  },
  vagas_status: {
    id: "vagas_status",
    rotulo: "Vagas por status",
    fonte: "vw_fato_vagas",
    formula: "soma(abertas + em_andamento + fechadas + canceladas)",
    unidade: "contagem",
    agg: "sum",
    sentido: "neutro",
    meta: null,
    grao_minimo: ["area", "mes"],
    sinonimos: [
      "vagas",
      "status das vagas",
      "abertas",
      "fechadas",
      "canceladas",
      "posicoes",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-08-24). Unidade `contagem`, que entrou no enum em 2026-08-24 (D-H45): vaga nao e pessoa, entao `FTE` afirmaria algo falso.",
  },
  variacao_de_capital_de_giro: {
    id: "variacao_de_capital_de_giro",
    rotulo: "Variação de capital de giro",
    fonte: "vw_fato_fin_mes, vw_fato_balanco_mes",
    formula: "ebitda - juros_pagos - impostos_sobre_lucro - fco (recorte)",
    unidade: "BRL_mi",
    agg: "sum",
    sentido: "menor_melhor",
    meta: null,
    grao_minimo: ["entidade", "mes"],
    sinonimos: [
      "variacao de capital de giro",
      "capital de giro consumiu",
      "giro consumiu",
      "o que o giro consumiu",
    ],
    decisao:
      "PROVISORIO (D-H03, 2026-09-03). Obtida por diferenca na ponte EBITDA -> caixa: positivo e caixa consumido pelo giro. E declaracao, nao coluna.",
  },
};

/** Quantas métricas o catálogo tem. Contado, nunca escrito. */
export const QUANTIDADE_DE_METRICAS = 114;

/**
 * Qual catálogo produziu um número (T-149).
 *
 * Viaja em `getMeta().versaoDoCatalogo`, para que "o número mudou" e "a
 * definição mudou" deixem de ser indistinguíveis. T-155 troca isto por versão
 * semântica com changelog; até lá é a identidade do conteúdo.
 */
export const VERSAO_DO_CATALOGO = "646c10f9e95b";
